[package]
name = "engine"
version = "0.1.0"
authors = ["David Atkins <gamecake1@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
cgmath = "0.18.0"
image = "0.19.0"
rand = "0.8.4"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
