[package]
name = "engine"
version = "0.1.0"
authors = ["David Atkins <gamecake1@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.10.0"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
